version: '3.6'
services:
  multisma2:
    container_name: multisma2
    image: multisma2:latest
    restart: unless-stopped
    volumes:
    - ./volumes/multisma2/log:/sillygoose/log
#    depends_on:
#    - mosquitto
#    - influxdb

